{
  "openapi": "3.0.2",
  "info": { "title": "Web App Gallery", "version": "1.0" },
  "servers": [{ "url": "http://localhost:3000" }],
  "paths": {
    "/api/me": {
      "get": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": ["user"],
        "summary": "get logged in users information",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": { "type": "string" },
                    "data": { "$ref": "#/components/schemas/User" }
                  },
                  "example": {
                    "status": "ok",
                    "data": {
                      "_id": "605767d7038aa8fbffc65fbb",
                      "firstName": "John",
                      "lastName": "Doe",
                      "email": "jondoe@example.com",
                      "password": "qwe123"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error",
                  "example": {
                    "status": "error",
                    "message": "Please authenticate to access"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/logout": {
      "post": {
        "security": [{ "cookieAuth": [] }],
        "tags": ["auth"],
        "summary": "logout user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": { "type": "string" },
                    "message": { "type": "string" }
                  },
                  "example": {
                    "status": "ok"
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "post": {
        "security": [],
        "tags": ["auth"],
        "summary": "login user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginCredentials"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": { "type": "string" },
                    "data": { "$ref": "#/components/schemas/User" }
                  },
                  "example": {
                    "status": "ok",
                    "data": {
                      "_id": "605767d7038aa8fbffc65fbb",
                      "firstName": "John",
                      "lastName": "Doe",
                      "email": "jondoe@example.com",
                      "password": "qwe123"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/api/signup": {
      "post": {
        "security": [],
        "tags": ["auth"],
        "summary": "create new user account",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/SignupUser"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": { "type": "string" },
                    "data": { "$ref": "#/components/schemas/User" }
                  },
                  "example": {
                    "status": "ok",
                    "data": {
                      "_id": "605767d7038aa8fbffc65fbb",
                      "firstName": "John",
                      "lastName": "Doe",
                      "email": "jondoe@example.com",
                      "password": "qwe123"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "ERROR",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/api/webapp": {
      "get": {
        "tags": ["webapp"],
        "description": "get paginated list of web applications",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "security": [
          {
            "cookieAuth": []
          }
        ],
        "tags": ["webapp"],
        "description": "submit a new web application",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "manifestURL": { "type": "string" }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "$ref": "#/components/responses/WebAppReturn"
          },
          "401": {
            "description": "unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Error"
          }
        }
      }
    },
    "/api/webapp/{id}": {
      "get": {
        "security": [],
        "tags": ["webapp"],
        "description": "view single web application",
        "parameters": [
          {
            "$ref": "#/components/parameters/AppID"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/WebAppReturn"
          },
          "400": {
            "$ref": "#/components/responses/Error"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "cookieAuth": {
        "type": "apiKey",
        "in": "cookie",
        "name": "token"
      }
    },
    "schemas": {
      "User": {
        "properties": {
          "_id": { "type": "string" },
          "firstName": { "type": "string" },
          "lastName": { "type": "string" },
          "email": { "type": "string" }
        }
      },
      "SignupUser": {
        "properties": {
          "firstName": { "type": "string" },
          "lastName": { "type": "string" },
          "email": { "type": "string" },
          "password": { "type": "string" }
        }
      },
      "LoginCredentials": {
        "properties": {
          "email": { "type": "string" },
          "password": { "type": "string" }
        }
      },
      "WebApp": {
        "properties": {
          "_id": { "type": "string" },
          "manifestURL": { "type": "string" },
          "startURL": { "type": "string" },
          "name": { "type": "string" },
          "description": { "type": "string" },
          "mobileWebAppCapable": { "type": "boolean" },
          "backgroundColor": { "type": "string" },
          "themeColor": { "type": "string" },
          "icons": {
            "type": "array",
            "items": {
              "properties": {
                "src": { "type": "string" },
                "purpose": { "type": "string" }
              }
            }
          }
        }
      },
      "Review": {
        "properties": {
          "_id": { "type": "string" },
          "rating": { "type": "integer" },
          "review": { "type": "string" },
          "user": { "$ref": "#/components/schemas/User" }
        }
      },
      "Error": {
        "properties": {
          "status": { "type": "string" },
          "message": { "type": "string" }
        }
      }
    },
    "responses": {
      "WebAppReturn": {
        "description": "OK",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "status": { "type": "string" },
                "data": { "$ref": "#/components/schemas/WebApp" }
              }
            }
          }
        }
      },
      "Error": {
        "description": "Standard error response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "parameters": {
      "AppID": {
        "name": "id",
        "in": "path",
        "schema": {
          "type": "integer"
        },
        "required": true,
        "description": "ID of requested application"
      }
    }
  }
}
